### ISSUE TITLE
Drupal8 benchmark is failing on PPC64

### ISSUE THREAD

**Issue by racardoso** [PPC64/hhvm#158]
HHVM last merge with upstream broke oss-performance Drupal8 benchmark on PPC64

### HHVM Version
HHVM upstream/master
HHVM next

### Standalone code, or other way to reproduce the problem
`hhvm perf.php --drupal8 --hhvm=$HHVM_PATH`

### Expected result
Siege results for Drupal8 test.

### Actual result
```
**************************
** 2016-11-07 07:12:51 CST
** Running sanity check

Warning: Failed to open http://rcardoso:8090/ () in /home/rcardoso/oss-performance/base/PerfTarget.php on line 30

Fatal error: Uncaught exception 'HH\InvariantException' with message 'Failed to find string "Read more" in http://rcardoso:8090/' in /home/rcardoso/oss-performance/base/PerfTarget.php:34
Stack trace:
#0 /home/rcardoso/oss-performance/base/PerfTarget.php(34): HH\invariant_violation()
#1 /home/rcardoso/oss-performance/base/PerfRunner.php(99): PerfTarget->sanityCheck()
#2 /home/rcardoso/oss-performance/base/PerfRunner.php(42): PerfRunner::RunWithOptionsAndEngine()
#3 /home/rcardoso/oss-performance/base/PerfRunner.php(17): PerfRunner::RunWithOptions()
#4 /home/rcardoso/oss-performance/perf.php(15): PerfRunner::RunWithArgv()
#5 /home/rcardoso/oss-performance/perf.php(19): perf_main()
#6 {main}
```

**Comment by racardoso** [comment]
Got a PHP Fatal Error. Need to check if the old HHVM version rise this error too.
```
PHP Fatal error:  Undefined class constant 'MYSQL_ATTR_USE_BUFFERED_QUERY' in /tmp/hhvm-nginxt2VRLr/drupal-8.0.0-beta11/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 78
Drush command terminated abnormally due to an unrecoverable error.                                                                                 [error]
Error: Undefined class constant 'MYSQL_ATTR_USE_BUFFERED_QUERY' in
/tmp/hhvm-nginxt2VRLr/drupal-8.0.0-beta11/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php, line 78
```

**Comment by racardoso** [comment]
After a long bisect i find the commit that breaks https://github.com/facebook/hhvm/commit/2deffa0

**Comment by racardoso** [comment]
This `bool ElideAutoloadInvokes = true;` is a new thing introduced on last merge and causing our problem is enabled by default.

**Comment by brunoalr** [comment]
@racardoso the commit that introduced the line you mentioned isn't https://github.com/facebook/hhvm/commit/2deffa0543d4f2c26cb4aa9b441ad1f9207f6644 ?

**Comment by racardoso** [comment]
@brunoalr you are right. Wrong ctrl+v. Thx

**Comment by racardoso** [comment]
I made `ElideAutoloadInvokes` disabled by default (see 1b79f82a588b2ed62018e765c55d4564ae5777ab). Now Drupal8 is running again. Note that commit won't fix the problem just disable that option. I'm still running tests on x86_64 to check if this is a problem that affects PPC64 only or x64 too.

**Comment by racardoso** [comment]
This problem seems to affect x86_64 too. A issue was been opened to Facebook: https://github.com/facebook/hhvm/issues/7477

**Comment by racardoso** [comment]
Beside this problem i find another error

```
***************************************************************
** 2016-11-10 07:23:59 CST
** Configuration: Drupal8PageCacheTarget on /usr/local/bin/hhvm

**************************
** 2016-11-10 07:23:59 CST
** Installing framework
PHP Fatal error:  Uncaught Error: Call to undefined function Drupal\Core\Cache\mb_check_encoding() in /tmp/hhvm-nginx01OGqH/drupal-8.0.0-beta11/core/lib/Drupal/Core/Cache/DatabaseBackend.php:435
Stack trace:
#0 /tmp/hhvm-nginx01OGqH/drupal-8.0.0-beta11/core/lib/Drupal/Core/Cache/DatabaseBackend.php(78): Drupal\Core\Cache\DatabaseBackend->normalizeCid('system.filter')
#1 /tmp/hhvm-nginx01OGqH/drupal-8.0.0-beta11/core/lib/Drupal/Core/Config/CachedStorage.php(93): Drupal\Core\Cache\DatabaseBackend->getMultiple(Array)
#2 /tmp/hhvm-nginx01OGqH/drupal-8.0.0-beta11/core/lib/Drupal/Core/Config/ConfigFactory.php(166): Drupal\Core\Config\CachedStorage->readMultiple(Array)
#3 /tmp/hhvm-nginx01OGqH/drupal-8.0.0-beta11/core/lib/Drupal/Core/Config/ConfigFactory.php(109): Drupal\Core\Config\ConfigFactory->doLoadMultiple(Array, true)
#4 /tmp/hhvm-nginx01OGqH/drupal-8.0.0-beta11/core/lib/Drupal/Core/Config/ConfigFactory.php(94): Drupal\Core\Config\ConfigFactory->doGet('system.filter')
#5 /tmp/hhvm-nginx01OGqH/drupal-8.0.0-beta11/core/lib/Drupa in /tmp/hhvm-nginx01OGqH/drupal-8.0.0-beta11/core/lib/Drupal/Core/Cache/DatabaseBackend.php on line 435
Drush command terminated abnormally due to an unrecoverable error.                                                                                 [error]
Error: Uncaught Error: Call to undefined function Drupal\Core\Cache\mb_check_encoding() in
/tmp/hhvm-nginx01OGqH/drupal-8.0.0-beta11/core/lib/Drupal/Core/Cache/DatabaseBackend.php:435
Stack trace:
#0 /tmp/hhvm-nginx01OGqH/drupal-8.0.0-beta11/core/lib/Drupal/Core/Cache/DatabaseBackend.php(78):
Drupal\Core\Cache\DatabaseBackend->normalizeCid('system.filter')
#1 /tmp/hhvm-nginx01OGqH/drupal-8.0.0-beta11/core/lib/Drupal/Core/Config/CachedStorage.php(93):
Drupal\Core\Cache\DatabaseBackend->getMultiple(Array)
#2 /tmp/hhvm-nginx01OGqH/drupal-8.0.0-beta11/core/lib/Drupal/Core/Config/ConfigFactory.php(166):
Drupal\Core\Config\CachedStorage->readMultiple(Array)
#3 /tmp/hhvm-nginx01OGqH/drupal-8.0.0-beta11/core/lib/Drupal/Core/Config/ConfigFactory.php(109):
Drupal\Core\Config\ConfigFactory->doLoadMultiple(Array, true)
#4 /tmp/hhvm-nginx01OGqH/drupal-8.0.0-beta11/core/lib/Drupal/Core/Config/ConfigFactory.php(94):
Drupal\Core\Config\ConfigFactory->doGet('system.filter')
#5 /tmp/hhvm-nginx01OGqH/drupal-8.0.0-beta11/core/lib/Drupa in
/tmp/hhvm-nginx01OGqH/drupal-8.0.0-beta11/core/lib/Drupal/Core/Cache/DatabaseBackend.php, line 435

**************************
** 2016-11-10 07:25:18 CST
** There is no setUpTest

**************************
** 2016-11-10 07:25:18 CST
** Starting Nginx
nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)

**************************
** 2016-11-10 07:25:18 CST
** Starting PHP Engine
running hphp...
all files saved in /tmp/hhvm-nginx01OGqH ...
running hphp took 0'19" (19737990 us) wall time
BootStats: mapping self...
BootStats: mapping self block done, took 1ms wall, 0ms cpu, 0 MB RSS
BootStats: pagein_self done, took 1ms wall, 5ms cpu, 0 MB RSS
BootStats: loading static content...
loaded file cache from /tmp/hhvm-nginx01OGqH/static.content
BootStats: loading static content block done, took 12ms wall, 13ms cpu, 2 MB RSS
BootStats: pthread_init done, took 13ms wall, 13ms cpu, 2 MB RSS
BootStats: Process::InitProcessStatics done, took 0ms wall, 0ms cpu, 0 MB RSS
BootStats: timezone_init done, took 0ms wall, 0ms cpu, 4 MB RSS

**************************
** 2016-11-10 07:25:41 CST
** Running sanity check

Warning: Failed to open http://rcardoso:8090/ () in /home/rcardoso/oss-performance/base/PerfTarget.php on line 30

Fatal error: Uncaught exception 'HH\InvariantException' with message 'Failed to find string "Read more" in http://rcardoso:8090/' in /home/rcardoso/oss-performance/base/PerfTarget.php:34
Stack trace:
#0 /home/rcardoso/oss-performance/base/PerfTarget.php(34): HH\invariant_violation()
#1 /home/rcardoso/oss-performance/base/PerfRunner.php(99): PerfTarget->sanityCheck()
#2 /home/rcardoso/oss-performance/base/PerfRunner.php(42): PerfRunner::RunWithOptionsAndEngine()
#3 /home/rcardoso/oss-performance/base/PerfRunner.php(17): PerfRunner::RunWithOptions()
#4 /home/rcardoso/oss-performance/perf.php(15): PerfRunner::RunWithArgv()
#5 /home/rcardoso/oss-performance/perf.php(19): perf_main()
#6 {main}

Warning: Failed to open http://localhost:8091/check-health (Failed to connect to localhost port 8091: Connection refused) in /home/rcardoso/oss-performance/base/HHVMDaemon.php on line 343
Terminated
```

This error don't happens when link php with hhvm with:

```
$  update-alternatives --config php
There are 2 choices for the alternative php (providing /usr/bin/php).

  Selection    Path                 Priority   Status
------------------------------------------------------------
  0            /usr/bin/php7.0       70        auto mode
 *1           /usr/local/bin/hhvm   60        manual mode
```

**Comment by racardoso** [comment]
solved the installing framework error installing some missing php modules:

```
php-mbstring
php-xml
```

But i still got a error if i don't use hhvm instead php.

**Comment by racardoso** [comment]
Seems solved by https://github.com/facebook/hhvm/issues/7477
